name: Build and Release Cross-Platform Binaries

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: AIImageTokenSaver.exe
            pyinstaller_cmd: pyinstaller --onefile --noconsole --icon src/tray_icon.ico --paths=src src/main.py
            upload_path: dist/AIImageTokenSaver.exe

          - os: macos-latest
            artifact_name: AIImageTokenSaver-mac
            pyinstaller_cmd: pyinstaller --onefile --windowed --icon src/tray_icon.icns --paths=src src/main.py
            upload_path: dist/AIImageTokenSaver-mac

          - os: ubuntu-latest
            artifact_name: AIImageTokenSaver-linux
            pyinstaller_cmd: pyinstaller --onefile --icon src/tray_icon.png --paths=src src/main.py
            upload_path: dist/AIImageTokenSaver-linux

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller pillow pyperclip pystray python-dotenv

      - name: Build Binary
        run: ${{ matrix.pyinstaller_cmd }}

      - name: Rename Windows Binary
        if: runner.os == 'Windows'
        run: mv dist/main.exe dist/${{ matrix.artifact_name }}

      - name: Rename non-Windows Binary
        if: runner.os != 'Windows'
        run: mv dist/main dist/${{ matrix.artifact_name }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.upload_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
