name: Build and Release Cross-Platform Binaries

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller pillow pyperclip pystray python-dotenv

      - name: Build Executable
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            pyinstaller --onefile --noconsole --icon src/tray_icon.ico src/main.py
          elif [ "$RUNNER_OS" == "macOS" ]; then
            pyinstaller --onefile --windowed --icon src/tray_icon.icns src/main.py
          elif [ "$RUNNER_OS" == "Linux" ]; then
            pyinstaller --onefile --icon src/tray_icon.png src/main.py
          fi

      - name: Rename Binaries
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            mv dist/main.exe dist/AIImageTokenSaver.exe
          elif [ "$RUNNER_OS" == "macOS" ]; then
            mv dist/main dist/AIImageTokenSaver-mac
          elif [ "$RUNNER_OS" == "Linux" ]; then
            mv dist/main dist/AIImageTokenSaver-linux
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/AIImageTokenSaver.exe
            dist/AIImageTokenSaver-mac
            dist/AIImageTokenSaver-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
