name: Build and Release Cross-Platform Binaries

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller pillow pyperclip pystray python-dotenv

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --noconsole --icon src/tray_icon.ico src/main.py

      - name: Build on macOS
        if: runner.os == 'macOS'
        run: |
          pyinstaller --onefile --windowed --icon src/tray_icon.icns src/main.py

      - name: Build on Linux
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile --icon src/tray_icon.png src/main.py

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/main
            dist/*.dmg
            dist/*.pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
